# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve --watch --port 4444'
# If you change this file, please restart the server process.


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Site settings
locale           : "en-US"
title            : "Stephen Griffies"
title_separator  : "-"
email            : Stephen.M.Griffies@gmail.com
url              : https://StephenGriffies.github.io
github_username  : StephenGriffies
name             : Stephen Griffies
description      : Physics and maths of the ocean circulation
teaser           : # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 00CCFF
  secondary-dark: 333

# pagination
#paginate: 5
#paginate_path: "/blog/page:num/"


# Build settings
markdown: kramdown

#theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes"

#theme: jekyll-theme-cayman
theme   : minima

plugins:
  - jekyll-feed


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:Stephen.M.Griffies@gmail.com
  - title: github
    url: https://github.com/StephenGriffies 
    
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
